channels:
  - conda-forge
dependencies:
  - r-base=4.1.0
  - r-caret
  - r-data.table
  - r-devtools
  - r-factoextra
  - r-fastNaiveBayes
  - r-fpc
  - r-ggrepel
  - r-glmnet
  - r-h2o
  - r-httr
  - r-IRkernel
  - r-jsonlite
  - r-lexicon
  - r-lsa
  - r-naivebayes
  - r-plot3D
  - r-plotly
  - r-qdap
  - r-quanteda
  - r-RCurl
  - r-readtext
  - r-RSelenium
  - r-rvest
# - r-sentimentanalysis
  - r-sentimentr
  - r-slam
  - r-spacyr
  - r-textclean
  - r-tidytext
  - r-tidyverse
  - r-tm
  - r-twfy
  - r-udpipe
  - r-uwot
  - r-wdman
  - r-webdriver
# - r-word2vec
  - r-wordcloud
  - r-xml2
