channels:
  - default
  - conda-forge
dependencies:
  # Python
  - geckodriver
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - selenium
  - transformers
  # R
  - r-base>=4.0
  - r-caret
  - r-data.table
  - r-devtools
# - r-doc2vec
  - r-factoextra
  - r-fastnaivebayes
  - r-fpc
  - r-ggrepel
  - r-glmnet
  - r-h2o
  - r-httr
  - r-irkernel>=1.1
  - r-jsonlite
  - r-lexicon
  - r-lsa
  - r-naivebayes
  - r-plot3D
  - r-plotly
  - r-qdap
  - r-quanteda
  - r-ranger
  - r-rcurl
  - r-readtext
  - r-reticulate
  - r-rselenium
  - r-rvest
# - r-sentimentanalysis
  - r-sentimentr
  - r-slam
  - r-spacyr
  - r-textclean
  - r-tidytext
  - r-tidyverse
  - r-tm
  - r-twfy
# - r-udpipe
  - r-uwot
  - r-wdman
  - r-webdriver
# - r-word2vec
  - r-wordcloud
  - r-xml2
